
* what is this?

this is [[https://github.com/uim/uim][uim]] module for input japanese text kana and kanji.

it uses [[https://en.wikipedia.org/wiki/Cangjie_input_method][cangjie]] to input kanji (by default).


* features

- specify multiple keystroke-to-string tables and switch between them.
- support wildcard (*, ?).

* requirement

- uim
- uim header (`libuim-dev' package in debian)
- gcc

* install

- compile
  + build libuim-switchtable.so
  + gcc, uim header file, libuim.so is required.
  + run make
#+BEGIN_EXAMPLE
$ make
#+END_EXAMPLE

- copy libuim-switchtable.so, *.scm to ~/.uim.d/plugin/
- copy table file (*.txt) to ~/.uim.d/tables/
- run following command
#+BEGIN_SRC
$ uim-module-manager --register switchtable --path ~/.uim.d/plugin
#+END_SRC

* how to use?

- start in console
#+BEGIN_SRC
$ uim-fep -u switchtable
#+END_SRC

- start in x
#+BEGIN_SRC
$ uim-xim --engine=switchtable
#+END_SRC

- default key bindings

| key        | command                 |
|------------+-------------------------|
| space      | commit                  |
| alt-c      | toggle candidate window |
| alt-a      | toggle auto commit      |
| alt-w      | toggle wildcard         |
| alt-p      | toggle prediction       |
| alt-1 / f6 | switch to rule1         |
| alt-2 / f7 | switch to rule2         |
| alt-3 / f8 | switch to rule3         |
| alt-4      | switch to rule4         |
| ...        | ...                     |
| alt-9      | switch to rule9         |

* config

edit ~/.uim

#+BEGIN_SRC scheme
;;; example setting
;; on/off key
(define-key switchtable-on-key? '("<Control>\\" "zenkaku-hankaku"))
(define-key switchtable-off-key? '("<Control>\\" "zenkaku-hankaku"))
;; bind switch rule1, rul2 to F1, F2
(define-key switchtable-switch-rule1-key? "F1")
(define-key switchtable-switch-rule2-key? "F2")
;; use hiragana, katakana
(define switchtable-rule-list
  '(((label . hiragana)
     (autocommit . #f)
     (prediction . #f)
     (wildcard . #t)
     (tablefile . "tables/hiragana.txt.txt"))
    ((label . katakana)
     (autocommit . #f)
     (prediction . #f)
     (wildcard . #t)
     (tablefile . "tables/katakana.txt"))))
#+END_SRC

* problems

- unable to assign switchtable-rule-list by uim-pref-*.
- project name.
